export const $LocalDateTime = {
  calendar: {},
  year: {},
  yearOfEra: {},
  era: {},
  month: {},
  dayOfYear: {},
  day: {},
  dayOfWeek: {},
  hour: {},
  clockHourOfHalfDay: {},
  minute: {},
  second: {},
  millisecond: {},
  tickOfSecond: {},
  tickOfDay: {},
  nanosecondOfSecond: {},
  nanosecondOfDay: {},
  timeOfDay: {},
  date: {},
};
