export const $User = {
  id: {},
  createdAt: {},
  updatedAt: {},
  createdBy: {},
  updatedBy: {},
  givenName: {},
  familyName: {},
  fullName: {},
  email: {},
  phoneNumber: {},
  cloudinaryPublicId: {},
  organizationUnitPath: {},
  organizationUnit: {},
  items: {},
};
